### ISSUE TITLE
Cant download the tzdbgen-1.0.1.jar

### ISSUE THREAD

**Issue by santhoshzen** [akashche/tzdbgen#1]
When i try to download the jar "tzdbgen-1.0.1.jar" it shows the below error.

> You do not have access to this repository.Return to the previous page or go back to your dashboard.

Help me to download the jar.

Thanks in advance.

**Comment by akashche** [comment]
It looks like old download link became invalid, I added 1.0.1 and 1.0.2 binaries to [releases](https://github.com/akashche/tzdbgen/releases) section.

**Comment by AnjanaM** [comment]
Thank you so much, Alex.
Downloaded from the link you shared :D

Regards,
Anjana M
